backend:
  name: github
  repo: relaxyd/jk-test
  branch: master
  site_domain: hungry-jones-845e42.netlify.com
  base_url: https://api.netlify.com
media_folder: "images"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Default Author", name: author, widget: string}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      
  - name: "pages"
    label: "Pages"    
    files:
      - name: "about"
        label: "About"
        file: "about.md"
        delete: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "index"
        label: "Index"
        file: "index.md"
        delete: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Body", name: "body", widget: "markdown"}